// Textos de /privacy e /terms nos 3 idiomas do site (22/09/2026 — antes só em inglês).
// Texto padrão de SaaS escrito pelo agente em 07/09; o Johnny ainda precisa revisar os
// dados legais. Ao mudar um idioma, mudar os três — a estrutura (seções) é a mesma.
import type { Lang } from './dictionary';

export type Bloco = { h?: string; p: string; b?: string };   // b = começo em negrito
export type Doc = { titulo: string; blocos: Bloco[] };
type Legal = { atualizado: string; duvidas: string; privacidade: Doc; termos: Doc };

export const LEGAL: Record<Lang, Legal> = {
  en: {
    atualizado: 'Last updated:',
    duvidas: 'Questions? Contact us at',
    privacidade: {
      titulo: 'Privacy Policy',
      blocos: [
        { p: 'LiveTranslate (“we”, “us”) provides live translation for churches and events at livetranslate.church. This policy explains what we collect and how we use it.' },
        { h: 'What we collect', b: 'Account data.', p: 'When a church creates an account we collect a name, email address and password — or, if you sign in with Google, the name and email address Google shares with us. We never see your Google password.' },
        { b: 'Church data.', p: 'Church name, public page address, logo, languages offered, and team member emails invited by the church admin.' },
        { b: 'Listener emails (optional).', p: 'Listeners may opt in with their email to receive the sermon transcript. We use it only for that purpose, and only for the church the listener subscribed to.' },
        { b: 'Service audio and transcripts.', p: 'During a live service, the speaker’s audio is processed in real time to produce translated audio and captions, and transcripts are stored so the church can download sermon PDFs. Audio is not kept after processing; transcripts belong to the church.' },
        { b: 'Technical data.', p: 'Basic logs (timestamps, connection counts, errors) needed to operate and improve the service. We do not sell data or run third-party advertising.' },
        { h: 'How we use it', p: 'To provide live translation, generate sermon transcripts, let churches manage their team, send service-related email (such as the sermon PDF), and keep the service secure and billed correctly.' },
        { h: 'Who we share it with', p: 'Only the processors needed to run the service: hosting, database and authentication (Supabase), real-time audio (LiveKit), speech translation (Google), email delivery (Resend) and payments when applicable (Stripe). Each receives only what it needs.' },
        { h: 'Your choices', p: 'Church admins can edit or delete their church data in the dashboard. Listeners can unsubscribe from sermon emails at any time, using the link in every email. To delete your account or request your data, email us.' },
        { h: 'Security & retention', p: 'Data is stored with encryption in transit and at rest by our providers. We keep data while the account is active; deleted accounts are removed within a reasonable period, except where the law requires otherwise.' },
        { h: 'Changes', p: 'If this policy changes materially, we will note it here with a new date.' },
      ],
    },
    termos: {
      titulo: 'Terms of Service',
      blocos: [
        { p: 'By using LiveTranslate (livetranslate.church) you agree to these terms.' },
        { h: 'The service', p: 'LiveTranslate provides real-time translation of live speech for churches and events, plus automatic transcripts. Translations are generated by machine and may contain inaccuracies; they are an aid, not a certified translation.' },
        { h: 'Accounts & subscriptions', p: 'The church admin is responsible for the account, its team members and its content. Paid plans renew monthly and can be cancelled anytime from the dashboard; the trial period is free and requires no card.' },
        { h: 'Acceptable use', p: 'Use the service only for lawful purposes and content you have the right to broadcast. We may suspend accounts that abuse the platform or put its operation at risk.' },
        { h: 'Content', p: 'Your sermons, transcripts and logo remain yours. You grant us only the license needed to process and deliver them through the service.' },
        { h: 'Liability', p: 'The service is provided “as is”. To the extent permitted by law, we are not liable for indirect damages or for inaccuracies in machine translation.' },
        { h: 'Changes', p: 'We may update these terms; continued use after an update means acceptance. Material changes will be noted here with a new date.' },
      ],
    },
  },

  es: {
    atualizado: 'Última actualización:',
    duvidas: '¿Preguntas? Escríbenos a',
    privacidade: {
      titulo: 'Política de privacidad',
      blocos: [
        { p: 'LiveTranslate (“nosotros”) ofrece traducción en vivo para iglesias y eventos en livetranslate.church. Esta política explica qué datos recopilamos y cómo los usamos.' },
        { h: 'Qué recopilamos', b: 'Datos de la cuenta.', p: 'Cuando una iglesia crea una cuenta, recopilamos nombre, correo electrónico y contraseña — o, si inicias sesión con Google, el nombre y el correo que Google comparte con nosotros. Nunca vemos tu contraseña de Google.' },
        { b: 'Datos de la iglesia.', p: 'Nombre de la iglesia, dirección de su página pública, logo, idiomas ofrecidos y los correos de los miembros del equipo invitados por el administrador.' },
        { b: 'Correos de los oyentes (opcional).', p: 'Los oyentes pueden dejar su correo para recibir la transcripción del sermón. Lo usamos solo para eso, y solo para la iglesia en la que se inscribieron.' },
        { b: 'Audio y transcripciones del culto.', p: 'Durante un culto en vivo, el audio del predicador se procesa en tiempo real para producir el audio traducido y los subtítulos, y las transcripciones se guardan para que la iglesia pueda descargar los PDF de los sermones. El audio no se conserva después del procesamiento; las transcripciones pertenecen a la iglesia.' },
        { b: 'Datos técnicos.', p: 'Registros básicos (horarios, número de conexiones, errores) necesarios para operar y mejorar el servicio. No vendemos datos ni mostramos publicidad de terceros.' },
        { h: 'Cómo los usamos', p: 'Para ofrecer la traducción en vivo, generar las transcripciones de los sermones, permitir que las iglesias administren su equipo, enviar correos relacionados con el servicio (como el PDF del sermón) y mantener el servicio seguro y correctamente facturado.' },
        { h: 'Con quién los compartimos', p: 'Solo con los proveedores necesarios para operar el servicio: alojamiento, base de datos y autenticación (Supabase), audio en tiempo real (LiveKit), traducción de voz (Google), envío de correos (Resend) y pagos, cuando corresponda (Stripe). Cada uno recibe solo lo que necesita.' },
        { h: 'Tus opciones', p: 'Los administradores de la iglesia pueden editar o eliminar los datos de su iglesia en el panel. Los oyentes pueden darse de baja de los correos del sermón en cualquier momento, con el enlace que va en cada correo. Para eliminar tu cuenta o solicitar tus datos, escríbenos.' },
        { h: 'Seguridad y conservación', p: 'Nuestros proveedores guardan los datos con cifrado en tránsito y en reposo. Conservamos los datos mientras la cuenta esté activa; las cuentas eliminadas se borran en un plazo razonable, salvo cuando la ley exija lo contrario.' },
        { h: 'Cambios', p: 'Si esta política cambia de forma importante, lo indicaremos aquí con una nueva fecha.' },
      ],
    },
    termos: {
      titulo: 'Términos del servicio',
      blocos: [
        { p: 'Al usar LiveTranslate (livetranslate.church) aceptas estos términos.' },
        { h: 'El servicio', p: 'LiveTranslate ofrece traducción en tiempo real de la palabra hablada para iglesias y eventos, además de transcripciones automáticas. Las traducciones son generadas por máquina y pueden contener imprecisiones; son una ayuda, no una traducción certificada.' },
        { h: 'Cuentas y suscripciones', p: 'El administrador de la iglesia es responsable de la cuenta, de los miembros de su equipo y de su contenido. Los planes pagos se renuevan mensualmente y se pueden cancelar en cualquier momento desde el panel; el período de prueba es gratuito y no requiere tarjeta.' },
        { h: 'Uso aceptable', p: 'Usa el servicio solo para fines legales y con contenido que tengas derecho a transmitir. Podemos suspender cuentas que abusen de la plataforma o pongan en riesgo su funcionamiento.' },
        { h: 'Contenido', p: 'Tus sermones, transcripciones y logo siguen siendo tuyos. Nos concedes solo la licencia necesaria para procesarlos y entregarlos a través del servicio.' },
        { h: 'Responsabilidad', p: 'El servicio se ofrece “tal como está”. En la medida en que la ley lo permita, no somos responsables por daños indirectos ni por imprecisiones de la traducción automática.' },
        { h: 'Cambios', p: 'Podemos actualizar estos términos; seguir usando el servicio después de una actualización implica aceptarla. Los cambios importantes se indicarán aquí con una nueva fecha.' },
      ],
    },
  },

  pt: {
    atualizado: 'Última atualização:',
    duvidas: 'Dúvidas? Fale com a gente em',
    privacidade: {
      titulo: 'Política de privacidade',
      blocos: [
        { p: 'O LiveTranslate (“nós”) oferece tradução ao vivo para igrejas e eventos em livetranslate.church. Esta política explica quais dados coletamos e como os usamos.' },
        { h: 'O que coletamos', b: 'Dados da conta.', p: 'Quando uma igreja cria uma conta, coletamos nome, e-mail e senha — ou, se você entrar com o Google, o nome e o e-mail que o Google compartilha conosco. Nunca vemos a sua senha do Google.' },
        { b: 'Dados da igreja.', p: 'Nome da igreja, endereço da página pública, logo, idiomas oferecidos e os e-mails dos membros da equipe convidados pelo administrador.' },
        { b: 'E-mails dos ouvintes (opcional).', p: 'Os ouvintes podem deixar o e-mail para receber a transcrição da pregação. Usamos o e-mail só para isso, e só para a igreja em que a pessoa se inscreveu.' },
        { b: 'Áudio e transcrições do culto.', p: 'Durante um culto ao vivo, o áudio do pregador é processado em tempo real para gerar o áudio traduzido e as legendas, e as transcrições são guardadas para que a igreja possa baixar os PDFs das pregações. O áudio não é guardado depois do processamento; as transcrições pertencem à igreja.' },
        { b: 'Dados técnicos.', p: 'Registros básicos (horários, número de conexões, erros) necessários para operar e melhorar o serviço. Não vendemos dados nem exibimos publicidade de terceiros.' },
        { h: 'Como usamos', p: 'Para oferecer a tradução ao vivo, gerar as transcrições das pregações, permitir que as igrejas gerenciem a equipe, enviar e-mails ligados ao serviço (como o PDF da pregação) e manter o serviço seguro e cobrado corretamente.' },
        { h: 'Com quem compartilhamos', p: 'Só com os fornecedores necessários para operar o serviço: hospedagem, banco de dados e autenticação (Supabase), áudio em tempo real (LiveKit), tradução de voz (Google), envio de e-mails (Resend) e pagamentos, quando houver (Stripe). Cada um recebe apenas o que precisa.' },
        { h: 'Suas escolhas', p: 'Os administradores da igreja podem editar ou excluir os dados da igreja no painel. Os ouvintes podem cancelar os e-mails das pregações a qualquer momento, pelo link que vai em cada e-mail. Para excluir sua conta ou pedir seus dados, escreva para nós.' },
        { h: 'Segurança e guarda', p: 'Nossos fornecedores guardam os dados com criptografia em trânsito e em repouso. Mantemos os dados enquanto a conta estiver ativa; contas excluídas são apagadas em prazo razoável, exceto quando a lei exigir o contrário.' },
        { h: 'Mudanças', p: 'Se esta política mudar de forma relevante, vamos indicar aqui, com uma nova data.' },
      ],
    },
    termos: {
      titulo: 'Termos de uso',
      blocos: [
        { p: 'Ao usar o LiveTranslate (livetranslate.church), você concorda com estes termos.' },
        { h: 'O serviço', p: 'O LiveTranslate oferece tradução em tempo real da fala ao vivo para igrejas e eventos, além de transcrições automáticas. As traduções são geradas por máquina e podem conter imprecisões; são um apoio, não uma tradução juramentada.' },
        { h: 'Contas e assinaturas', p: 'O administrador da igreja é responsável pela conta, pelos membros da equipe e pelo conteúdo. Os planos pagos renovam todo mês e podem ser cancelados a qualquer momento pelo painel; o período de teste é gratuito e não pede cartão.' },
        { h: 'Uso aceitável', p: 'Use o serviço apenas para fins legais e com conteúdo que você tenha o direito de transmitir. Podemos suspender contas que abusem da plataforma ou coloquem o funcionamento dela em risco.' },
        { h: 'Conteúdo', p: 'Suas pregações, transcrições e logo continuam sendo seus. Você nos concede apenas a licença necessária para processá-los e entregá-los por meio do serviço.' },
        { h: 'Responsabilidade', p: 'O serviço é oferecido “no estado em que se encontra”. Na medida permitida por lei, não nos responsabilizamos por danos indiretos nem por imprecisões da tradução automática.' },
        { h: 'Mudanças', p: 'Podemos atualizar estes termos; continuar usando o serviço depois de uma atualização significa aceitá-la. Mudanças relevantes serão indicadas aqui, com uma nova data.' },
      ],
    },
  },
};
